import { Analytics } from '@vercel/analytics/react';

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FIQ-GPT',
  description: 'Generated BY My Hand',
  manifest : '/manifest.json',
  icons: {apple: '/icon.png'},
  themeColor : '#fff'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
